Add env variables for forcing the buildpack to fail

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -5,4 +5,9 @@ echo $1
 echo $2
 echo $3
 env
+if [ -n "$BUILDPACK_COMPILE_FAIL" ]
+then
+  echo "detect failed because BUILDPACK_COMPILE_FAIL was set"
+  exit 1
+fi
 echo "Done"
diff --git a/bin/detect b/bin/detect
--- a/bin/detect
+++ b/bin/detect
@@ -1,4 +1,9 @@
 #!/bin/sh
 echo "DETECT=============="
 echo $1
+if [ -n "$BUILDPACK_DETECT_FAIL" ]
+then
+  echo "detect failed because BUILDPACK_DETECT_FAIL was set"
+  exit 1
+fi
 exit 0
